object Versions {

    const val LIFECYCLE = "2.2.0"
    const val NAV = "2.3.1"
    const val KTS = "1.3.2"
    const val CONSTRAINT_LAYOUT = "2.0.4"
    const val HILT_LIFECYCLE = "1.0.0-alpha01"
    const val KOTLIN = "1.4.20"
    const val HILT = "2.31.2-alpha"
    const val COROUTINES = "1.3.0"
    const val RETROFIT = "2.9.0"
    const val APP_COMPAT = "1.2.0"
    const val MATERIAL = "1.3.0-alpha04"
    const val BUILD_TOOLS = "4.1.1"
    const val OKHTTP = "3.14.0"
    const val GSON = "2.8.6"
    const val STETHO = "1.5.1"
    const val TIMBER = "4.1.2"
    const val CHUCK = "1.1.0"
    const val GLIDE = "4.11.0"
    const val SWIPE_REFRESH = "1.1.0"
    const val SAFE_ARGS = "2.3.2"
    const val UTILS = "1.9.12"
    const val MOCKITO = "3.3.3"
    const val JUNIT = "4.13.1"
    const val ARCH_CORE_TEST = "2.1.0"
    const val ESPRESSO = "3.3.0"
    const val FRAGMENT_VERSION = "1.2.5"
    const val ANDROID_TEST = "1.1.0"
}